### ISSUE TITLE
lib-sass 可以更新了

### ISSUE THREAD

**Issue by jiangyuan** [fis-dev/fis-sass#4]
如题，3.2.x 的 lib-sass 有大提升。

**Comment by 2betop** [comment]
收到，但是目前时间精力有线，麻烦多等会。

因为编译机 node 升级了，后续也许就直接用 node-sass 了。

**Comment by jiangyuan** [comment]
我也觉得 node-sass 可以直接搞起。

**Comment by 2betop** [comment]
https://github.com/fex-team/fis-parser-node-sass

**Comment by jiangyuan** [comment]
效率！
